name: CI/CD - Chat Agent Streamlit

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v3

      - name: ♻️ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ↑ Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: ✅ Basic CI Test - Check Streamlit app loads
        run: |
          python -c "import streamlit"
          echo "Streamlit app validated."

      - name: 🚀 Deploy to Streamlit Cloud
        run: |
          echo "NOTE: Deployment to Streamlit Cloud is managed automatically via GitHub repo link."
          echo "No manual deployment needed here unless you use Streamlit Sharing CLI."

      # Optional: linting or testing
      # - name: Run lint checks
      #   run: flake8 src/ frontend/ --ignore=E501

      # - name: Run unit tests
      #   run: pytest tests/
